### PR TITLE
Added some menus with no functionality

### PR DESCRIPTION
**Pull request by jybroyl**

### CODE REVIEW

**Comment by maxshort** [comment]
menu issue
Looks good except the buttons go off screen. I think we need [anchors](http://docs.unity3d.com/Manual/UIBasicLayout.html). Also, I think we should have a consistent background on all the menus. I can start on code after that.

**Comment by cdjobe** [comment]
I can confirm that the buttons go off screen. Everything is there, though. Also like the sliders to change characters.

**Comment by jybroyl** [comment]
unitylandrunmenu

**Comment by maxshort** [comment]
Ha ha crap. Let me see if I can reproduce that on my computer to figure out what's going on.

**Comment by maxshort** [comment]
+1 looks good to me

**Pull request merged**
