### PR TITLE
updated second track to mimic first as well as smoothing AI movment

### PR DESCRIPTION
**Pull request by aww815**

### CODE REVIEW

**Comment by maxshort** [comment]
Couple issues...
- Can't play track02 at all
- Not sure if I'm triggering a spinout correctly

**Comment by maxshort** [comment]
Also saw that assignment says "IMPORTANT: If you find the source of a similar Unity game online, it is considered inappropriate to use part or all of that code in your solution. This is to be your team’s code." 

At the very least, we probably need to appropriately credit the authors. Where is some of this code from?

**Comment by aww815** [comment]
also added collider to rest of track 1 and 2

**Comment by maxshort** [comment]
I have merged this code. Not sure why it is showing conflicts

**Pull request closed without merging**
