### PR TITLE
Hud and background music

### PR DESCRIPTION
**Pull request by aww815**
added hud and background music

### CODE REVIEW

**Comment by maxshort** [comment]
Looks good overall though I haven't cloned it to listen to the music etc. A couple questions:
1. Why did the `Scenes` folder move to `_Scenes`?
2. It looks like the `incLap` in the UI script only updates the internal variable and not the actual text. This might not be a problem anyway because I don't think we'll have laps for the game. (Have to ask Carson to make sure on that)

**Comment by aww815** [comment]
Renamed the scenes folder for ease , underscore will make sure it stays at the top of the list, and im sure the list will get quite long after a wile, and u may be right about the laps i can  have a look at it and fix it if we end up using laps else it can jus be easly removed

**Comment by maxshort** [comment]
OK. The renaming is fine. I would suggest moving removing the laps for now (we can always use Git to go back into the commit history) but we can confirm with @cdjobe that the track does not have laps.

**Comment by cdjobe** [comment]
Definitely like the music and everything looks solid.

**Comment by maxshort** [comment]
OK Cool. @aww815 When you remove the lap counter I will merge this

**Comment by aww815** [comment]
ok i removed the laps

**Pull request merged**
